# Many of these values are defaults taken from:
# https://docs.codecov.com/docs/commit-status
coverage:
  status:
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
    project:
      default:
        # base
        target: 100%
        threshold: 0%
        base: auto
