blank_issues_enabled: true
contact_links:
  - name: 🆕 Create new issue
    url: https://new-issue.ant.design
    about: The issue which is not created via https://new-issue.ant.design will be closed immediately.
  - name: 🆕 创建一个新 Issue
    url: https://new-issue.ant.design
    about: ⚠️ 注意请不要使用上面的 Report a vulnerability 报告问题，这是用来报告安全漏洞的。不是用 https://new-issue.ant.design 创建的 issue 会被机器人自动关闭。
