name: 📦 Compressed Size

on:
  workflow_run:
    workflows: ["✅ test"]
    types:
      - completed
      - requested

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pattern: "./dist/**/*.min.{js,css}"
        build-script: "dist"
