name: DingTalk Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dingtalk robot message
        uses: northwang-lucky/chatbot-webhook-client@v1.1.1
        with:
          app: DingTalk
          # webhook: "https://oapi.dingtalk.com/robot/send?access_token=${{ secrets.DING_TALK_ACCESS_TOKEN }}"
          webhook: "https://oapi.dingtalk.com/robot/send?access_token=dd88546da75f580089cb9a8849dec0537004583babe2e55b09daddf001b46d03"
          template: >-
            {
              "msgtype": "markdown",
              "markdown": {
                "title": "🔥 @${{ github.event.discussion.user.login }} 创建了讨论：${{ github.event.discussion.title }} ${{ github.event.discussion.html_url }}",
                "text": "### 🔥 @${{ github.event.discussion.user.login }} 创建了讨论 \n [${{ github.event.discussion.title }}](${{ github.event.discussion.html_url }}) <hr /> \n > 💬 欢迎前往 GitHub 进行讨论，社区可能需要你的帮助。"
              }
            }
