name: CI
on: [push]
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
      - run: npm install && npm install -g @lhci/cli@0.4.x
      - run: npm run site
      - run: lhci autorun --upload.target=temporary-public-storage
