name: Continuous Releases

on:
  workflow_run:
    workflows: ["✅ test"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # ========== Prepare package ==========
      - name: restore cache from package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      # ========== build ==========
      - name: Build
        run: npm run build

      # ========== Prepare examples ==========
      - name: Clear examples
        run: rm -rf examples

      - name: Clone examples
        uses: actions/checkout@v4
        with:
          repository: ant-design/ant-design-examples
          path: examples

      - name: Modify examples
        run: npx tsx scripts/prepare-examples.ts

      - run: npx pkg-pr-new publish --template './examples/examples/*'
