# Each PR will build preview site that help to check code is work as expect.

name: Preview Deploy

on:
  workflow_run:
    workflows: ["Preview Build"]
    types:
      - completed

jobs:
  deploy-site:
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: download site artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: site-${{ github.event.workflow_run.pull_requests[0].number }}

      - name: upload surge service
        run: |
          export DEPLOY_DOMAIN=https://preview-${{ github.event.pull_request.number }}-ant-design.surge.sh
          npx surge --project ./ --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}