# When `preview-build` start. Leave a message on the PR

name: Preview Start

on:
  workflow_run:
    workflows: ["Preview Build"]
    types:
      - requested

jobs:
  deploy-site:
    name: deploy preview
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: update status comment
        uses: actions-cool/maintain-one-comment@v1.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            ![Prepare preview](https://user-images.githubusercontent.com/5378891/72351368-2c979e00-371b-11ea-9652-eb4e825d745e.gif)
            <!-- AUTO_PREVIEW_HOOK -->
          body-include: '<!-- AUTO_PREVIEW_HOOK -->'
          number: ${{ github.event.workflow_run.pull_requests[0].number }}