name: Publish to github-package
on: push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: install
        run: npm install

      - name: compile
        run: npm run compile

      - name: dist
        run: npm run dist

      - name: upload es
        uses: actions/upload-artifact@master
        with:
          name: esm
          path: es

      - name: upload lib
        uses: actions/upload-artifact@master
        with:
          name: cjs
          path: lib

      - name: upload dist
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    needs: compile

    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: download es
        uses: actions/download-artifact@master
        with:
          name: esm
          path: es

      - name: download lib
        uses: actions/download-artifact@master
        with:
          name: cjs
          path: lib

      - name: download dist
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
