name: Publish to github-package
on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@master

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: install
        run: npm install

      - name: compile
        run: npm run compile

      - name: dist
        run: npm run dist

      - name: set registry
        run: node scripts/set-registry.js

      - name: publish
        run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
