# When pushing a tag. this workflow will trigger site deployment and fixed version address comments

name: Deploy website
on:
  push:
    tags:
      - '5.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    if: (startsWith(github.ref, 'refs/tags/') && (contains(github.ref_name, '-') == false)) || github.event_name == 'workflow_dispatch'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: cache package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: create package-lock.json
        run: npm i --package-lock-only --ignore-scripts

      - name: hack for single file
        run: |
          if [ ! -d "package-temp-dir" ]; then
            mkdir package-temp-dir
          fi
          cp package-lock.json package-temp-dir
      - name: cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: install
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: npm ci

  build-site:
    name: release site
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: restore cache from package-lock.json
        uses: actions/cache@v4
        with:
          path: package-temp-dir
          key: lock-${{ github.sha }}

      - name: restore cache from node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-temp-dir/package-lock.json') }}

      - name: build site
        run: npm run predeploy
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: build dist and bundle analyzer report
        run: npm run dist
        env:
          ANALYZER: 1
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-site
          path: _site
          # retention-days: 5 # Follow default value

  deploy:
    runs-on: ubuntu-latest
    needs: [setup, build-site]
    steps:
      - name: download site artifact
        uses: actions/download-artifact@v4
        with:
          name: release-site
          path: _site

      - name: Get version
        id: publish-version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | sed 's/\./-/g')" >> $GITHUB_OUTPUT

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true

      # Since force_orphan will not trigger Sync to Gitee, we need to force run it here
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ant-design/ant-design.git'
          destination-repo: 'git@gitee.com:ant-design/ant-design.git'

      - name: Deploy to Surge (with TAG)
        run: |
          export DEPLOY_DOMAIN=ant-design-${{ steps.publish-version.outputs.VERSION }}.surge.sh
          cp report.html ./_site
          npx surge --project ./_site --domain $DEPLOY_DOMAIN --token ${{ secrets.SURGE_TOKEN }}

      - name: Create Commit Comment
        uses: peter-evans/commit-comment@v3
        with:
          body: |
            - Documentation site for this release: https://ant-design-${{ steps.publish-version.outputs.VERSION }}.surge.sh
            - Webpack bundle analyzer report page: https://ant-design-${{ steps.publish-version.outputs.VERSION }}.surge.sh/report.html

  # https://github.com/ant-design/ant-design/discussions/40479
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [setup, build-site]
    if: startsWith(github.ref, 'refs/tags/') && (contains(github.ref_name, '-') == false)
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: download site artifact
        uses: actions/download-artifact@v4
        with:
          name: release-site
          path: _site

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Format Docker Image tags
        id: build-docker-version
        shell: bash
        run: |
          # 5.2.2 => output: 5, 5.2, 5.2.2
          docker_name=${{ github.repository }} # ant-design/ant-design
          version=${{ github.ref_name }}
          major=$(echo $version | cut -d '.' -f 1)
          minor=$(echo $version | cut -d '.' -f 2)
          # patch=$(echo $version | cut -d '.' -f 3)

          tags="$docker_name:$version,$docker_name:$major.$minor,$docker_name:$major"

          # If it's not manually triggered, then it's just adding a latest tag
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            tags="$tags,$docker_name:latest"
          fi

          echo "tags=$tags" >> $GITHUB_OUTPUT


      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.build-docker-version.outputs.tags }}

