name: 📦 Size Limit

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: preactjs/compressed-size-action@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - uses: andresz1/size-limit-action@v1.4.0
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        skip_step: install
