# Origin Source
# https://github.com/ant-design/ant-design/blob/79f566b7f8abb1012ef55b0d2793bfdf5595b85d/.github/workflows/test.yml
name: ✅ test

on: [push, pull_request]

# Cancel prev CI if new commit come
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: install
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: lint
        run: npm run lint
    needs: setup

  tsx-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: tsx-demo
        run: npm run check-ts-demo
    needs: setup

  check_metadata:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: check demo
        run: node ./scripts/check-demo.js
    needs: setup

  ################################ Dist ################################
  dist:
    name: dist
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache dist
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ github.sha }}

      - name: dist
        run: npm run dist
        env:
          NODE_OPTIONS: --max_old_space_size=4096
    needs: setup

  ############################### Style ################################
  style-compile:
    name: es style compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: restore cache from es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: lessc component
        run: npx lessc --js ./es/button/style/index.less

      - name: lessc mixins
        run: npx lessc --js ./es/style/mixins/index.less
    needs: compile

  style-dist:
    name: dist style compile
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: restore cache from lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: restore cache from es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: restore cache from dist
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ github.sha }}

      - name: lessc default
        run: npx lessc --js ./dist/antd.less

      - name: lessc dark
        run: npx lessc --js ./dist/antd.dark.less

      - name: lessc variable
        run: npx lessc --js ./dist/antd.variable.less
    needs: [compile, dist]

  ################################ Test ################################
  normal-test:
    name: test
    strategy:
      matrix:
        react: ['16', '17', '18']
        module: ['dom', 'node', 'dist']
    env:
      REACT: ${{ matrix.react }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: install react 16
        if: ${{ matrix.react == '16' }}
        run: npm run install-react-16

      - name: install react 17
        if: ${{ matrix.react == '17' }}
        run: npm run install-react-17

      - name: install react 18
        if: ${{ matrix.react == '18' }}
        run: npm run install-react-18

      - name: restore cache from dist
        if: ${{ matrix.module == 'dist' }}
        uses: actions/cache@v3
        with:
          path: dist
          key: dist-${{ github.sha }}

      - name: check
        if: ${{ matrix.module == 'dist' }}
        run: node ./tests/dekko/dist.test.js

      # 17 only
      - name: bundlesize
        if: ${{ matrix.module == 'dist' && matrix.react == '17' }}
        run: npm run bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}

      # dom test
      - name: dom test
        if: ${{ matrix.module == 'dom' }}
        run: npm test -- -w 1 --coverage

      # > 17 only
      - name: coverage
        if: ${{ matrix.module == 'dom' && matrix.react == '17' }}
        run: bash <(curl -s https://codecov.io/bash)

      # node test
      - name: node test
        if: ${{ matrix.module == 'node' }}
        run: npm run test-node

      # dist test
      - name: dist test
        if: ${{ matrix.module == 'dist' }}
        run: npm test
        env:
          LIB_DIR: dist
    needs: [setup, dist]

  ########################### Compile & Test ###########################
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: cache lib
        uses: actions/cache@v3
        with:
          path: lib
          key: lib-${{ github.sha }}

      - name: cache es
        uses: actions/cache@v3
        with:
          path: es
          key: es-${{ github.sha }}

      - name: compile
        run: npm run compile

      - name: check
        run: node ./tests/dekko/lib.test.js
    needs: setup

  compiled-module-test:
    name: module test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        react: ['16', '17', '18']
        module: [lib, es]
    env:
      REACT: ${{ matrix.react }}
    steps:
      - name: checkout
        # lib only run in master branch not in pull request
        if: ${{ github.event_name != 'pull_request' || matrix.module != 'lib' }}
        uses: actions/checkout@v3

      - name: restore cache from ${{ matrix.module }}
        # lib only run in master branch not in pull request
        if: ${{ github.event_name != 'pull_request' || matrix.module != 'lib' }}
        uses: actions/cache@v3
        with:
          path: ${{ matrix.module }}
          key: ${{ matrix.module }}-${{ github.sha }}

      - name: install react 16
        if: ${{ matrix.react == '16' && (github.event_name != 'pull_request' || matrix.module != 'lib') }}
        run: npm run install-react-16

      - name: install react 17
        if: ${{ matrix.react == '17' && (github.event_name != 'pull_request' || matrix.module != 'lib') }}
        run: npm run install-react-17

      - name: install react 18
        if: ${{ matrix.react == '18' && (github.event_name != 'pull_request' || matrix.module != 'lib') }}
        run: npm run install-react-18

      - name: test
        # lib only run in master branch not in pull request
        if: ${{ github.event_name != 'pull_request' || matrix.module != 'lib' }}
        run: npm test
        env:
          LIB_DIR: ${{ matrix.module }}
    needs: compile
