name: Trigger Argos with white-listed PRs

on: [push, pull_request]

permissions:
  contents: read

jobs:
  trigger_argos_with_whitelist_prs:
    runs-on: ubuntu-latest
    if: github.actor == 'kiner-tang'
    env:
      ARGOS_TOKEN: ${{ secrets.ARGOS_TOKEN }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install node_modules
        run: yarn
      - name: Build dist file
        run: npm run dist:esbuild
      - name: Run image screenshot tests
        run: npm run test-image
      - name: Upload screenshots to Argos CI
        run: npm run argos