# Each PR will visual-regression diff that help to check code is work as expect.

name: 👀 Visual Regression Diff Finish

on:
  pull_request

permissions:
  contents: read

jobs:
  download-visual-regression-report:
    name: download visual-regression report
    permissions:
      actions: read # for dawidd6/action-download-artifact to query and download artifacts
      issues: write  # for actions-cool/maintain-one-comment to modify or create issue comments
      pull-requests: write  # for actions-cool/maintain-one-comment to modify or create PR comments
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Save PR id to output
      - name: save PR id
        id: pr
        run: echo "id=$(<visual-regression-pr-id.txt)" >> $GITHUB_OUTPUT

      # unzip report and then upload them to oss
      - name: upload visual-regression report
        id: report
        env:
          ALI_OSS_AK_ID: ${{ secrets.ALI_OSS_AK_ID }}
          ALI_OSS_AK_SECRET: ${{ secrets.ALI_OSS_AK_SECRET }}
          PR_ID: ${{ steps.pr.outputs.id }}
        run: |
          echo "✅ Uncompress Finished"
          echo $ALI_OSS_AK_ID

          rm package.json
          npm i ali-oss --no-save
          echo "✅ Install `ali-oss` Finished"

